---
- name: Set generic SUSE specific distro facts
  set_fact:
    is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    is_leap: '{{ "Leap" in ansible_distribution }}'
    is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'

- name: Verify SLE/SLED systems are being registered
  fail:
    msg: "System is SLE/SLED, must include SUSE registration info on playbooks/secret.yml with suse_register_system and suse_registration_code variables set, refer to devconfig README for more information"
  when:
    - 'is_sle|bool'
    - 'not suse_register_system|bool'

- name: Prepare packages source list and register machine
  become: yes
  become_method: sudo
  script:
    cmd: "{{ role_path }}/scripts/prepare_suse_repos.sh --register-system-code {{ suse_registration_code }}"
  when:
    - suse_register_system|bool
    - suse_registration_code != 0

- name: Prepare packages source list
  become: yes
  become_method: sudo
  script:
    cmd: "{{ role_path }}/scripts/prepare_suse_repos.sh"
  when:
    - not suse_register_system|bool
    - not is_sle

- name: Install packages we typically care about
  become: yes
  become_method: sudo
  zypper:
    name:
      - nvme-cli
      - bison
      - flex
      - git-core
      - e2fsprogs
      - xfsprogs
      - xfsdump
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - libtool
      - psmisc
      - sed
      - vim
    state: present
