---
- name: Install packages we typically care about
  become: yes
  become_method: sudo
  zypper:
    name:
      - nvme-cli
      - bison
      - flex
      - git
      - e2fsprogs
      - xfsprogs
      - xfsdump
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - indent
      - libtool
      - psmisc
      - sed
      - vim
    state: present
