---
- name: Set generic SUSE specific distro facts
  set_fact:
    is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    is_leap: '{{ "Leap" in ansible_distribution }}'
    is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'

- name: Set SLE specific version labels to make checks easier
  set_fact:
    is_sle10: '{{ ansible_distribution_major_version == "10" }}'
    is_sle11: '{{ ansible_distribution_major_version == "11" }}'
    is_sle12: '{{ ansible_distribution_major_version == "12" }}'
    is_sle15: '{{ ansible_distribution_major_version == "15" }}'
    is_sle10sp3: '{{ ansible_distribution_version == "10.3" }}'
    is_sle11sp1: '{{ ansible_distribution_version == "11.1" }}'
    is_sle11sp4: '{{ ansible_distribution_version == "11.4" }}'
    is_sle12sp1: '{{ ansible_distribution_version == "12.1" }}'
    is_sle12sp3: '{{ ansible_distribution_version == "12.3" }}'
    is_sle15sp2: '{{ ansible_distribution_version == "15.2" }}'
  when:
    - is_sle|bool

- name: The default is to assume we have figured out how to add repos for each
  set_fact:
    repos_will_be_added: true

- name: Disable things which require a repo to be set but that cannot be done
  set_fact:
    repos_will_be_added: false
  when:
    - is_sle|bool
    - is_sle10|bool or is_sle11|bool

- name: The default is to assume all distro supports nvme-utils
  set_fact:
    lacks_nvme_utils: false

- name: Does this release lack nvme-utils
  set_fact:
    lacks_nvme_utils: true
  when:
    - is_sle|bool
    - is_sle10|bool or is_sle11|bool or is_sle12sp1|bool

- name: Verify SLE/SLED systems are being registered
  fail:
    msg: "System is SLE/SLED, must include SUSE registration info on playbooks/secret.yml with suse_register_system and suse_registration_code variables set, refer to devconfig README for more information"
  when:
    - 'is_sle|bool'
    - 'not suse_register_system|bool'

- name: Prepare packages source list and register machine
  become: yes
  become_method: sudo
  script:
    cmd: "{{ role_path }}/scripts/prepare_suse_repos.sh --register-system-code {{ suse_registration_code }}"
  when:
    - suse_register_system|bool
    - repos_will_be_added|bool
    - suse_registration_code != 0

- name: Prepare packages source list
  become: yes
  become_method: sudo
  script:
    cmd: "{{ role_path }}/scripts/prepare_suse_repos.sh"
  when:
    - not suse_register_system|bool
    - not is_sle|bool
    - repos_will_be_added|bool

- name: Install nvme tools
  become: yes
  become_method: sudo
  zypper:
    name:
      - nvme-cli
    state: present
  when:
    - repos_will_be_added|bool
    - not lacks_nvme_utils|bool

- name: Install packages we typically care about
  become: yes
  become_method: sudo
  zypper:
    name:
      - bison
      - flex
      - git-core
      - e2fsprogs
      - xfsprogs
      - xfsdump
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - libtool
      - psmisc
      - sed
      - vim
      - screen
      - fio
      - libaio-devel
      - diffutils
    state: present
  when:
    - repos_will_be_added|bool
