---
- name: Import optional debian specific variables
  include_vars: "{{ item }}"
  with_first_found:
    files:
      - "debian.yml"
    skip: true
  tags: vars
  when: ansible_facts['os_family']|lower == 'debian'

- name: Import optional suse specific variables
  include_vars: "{{ item }}"
  with_first_found:
    files:
      - "suse.yml"
    skip: true
  tags: vars
  when: ansible_facts['os_family']|lower == 'suse'

- name: Import optional redhat specific variables
  include_vars: "{{ item }}"
  with_first_found:
    files:
      - "redhat.yml"
    skip: true
  tags: vars
  when: ansible_facts['os_family']|lower == 'redhat'

# tasks to install dependencies
- name: Distribution specific setup
  import_tasks: debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'
- import_tasks: suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'
- import_tasks: redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'
