---
- name: Import optional user secret specific variables
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "secret.yml"
  tags: vars

- name: Import optional distribution specific variables
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "{{ ansible_facts['os_family']|lower }}.yml"
  tags: vars

# tasks to install dependencies
- name: Distribution specific setup
  import_tasks: debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'
- import_tasks: suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'
- import_tasks: redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'
